version: "3.13"
services:
  fastapi_backend:
    build: ./backend
    image: fastapi-image:latest
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    links:
      - ollama
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: /bin/sh -c "ollama pull deepseek-r1:1.5b && ollama serve"

volumes:
  ollama_data:
