services:
  llm_be:
    build: ./llm-be
    image: llm-be-image:latest
    container_name: llm-be
    ports:
      - "8001:8001"
    depends_on:
      - ollama
    links:
      - ollama

  llm_fe:
    build: ./llm-fe
    image: llm-fe-image:latest
    container_name: llm-fe
    network_mode: "host"
    depends_on:
      - llm_be
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # entrypoint: /bin/sh -c "ollama pull deepseek-r1:1.5b && ollama serve"

volumes:
  ollama_data:
